package auth_test

import (
	"context"
	"errors"
	"testing"
	"time"

	"golang.org/x/crypto/bcrypt"

	"github.com/eprisi/absensi-next/services/api/internal/domain"
	"github.com/eprisi/absensi-next/services/api/internal/platform/authtoken"
	"github.com/eprisi/absensi-next/services/api/internal/repo"
	"github.com/eprisi/absensi-next/services/api/internal/testutil"
	"github.com/eprisi/absensi-next/services/api/internal/usecase/auth"
)

func newService(t *testing.T) auth.Service {
	t.Helper()
	gdb := testutil.NewDB(t)
	issuer := authtoken.NewIssuer("test-secret")
	return auth.NewService(
		repo.NewEmployeeRepo(gdb),
		repo.NewUserRepo(gdb),
		issuer,
		repo.NewRevokedTokenRepo(gdb),
		15*time.Minute,
		30*24*time.Hour,
	)
}

// D-12/CLAUDE.md §8: bcrypt hashes generated by the legacy Laravel system
// must verify correctly here with no migration/rehash step. bcrypt.
// GenerateFromPassword stands in for "a hash minted by some other bcrypt
// implementation" -- the point under test is that our verify path
// (bcrypt.CompareHashAndPassword) works on any valid bcrypt hash, not one
// generated by our own code specifically.
func TestLoginEmployee_AcceptsPreexistingBcryptHash(t *testing.T) {
	gdb := testutil.NewDB(t)
	hash, err := bcrypt.GenerateFromPassword([]byte("legacy-password"), bcrypt.DefaultCost)
	if err != nil {
		t.Fatalf("generate hash: %v", err)
	}
	if err := gdb.Create(&domain.Employee{NIK: "0001", FullName: "Legacy", PasswordHash: string(hash), IsActive: true}).Error; err != nil {
		t.Fatalf("seed employee: %v", err)
	}

	issuer := authtoken.NewIssuer("test-secret")
	svc := auth.NewService(repo.NewEmployeeRepo(gdb), repo.NewUserRepo(gdb), issuer, repo.NewRevokedTokenRepo(gdb), 15*time.Minute, 30*24*time.Hour)

	tokens, emp, err := svc.LoginEmployee(context.Background(), "0001", "legacy-password")
	if err != nil {
		t.Fatalf("expected login to succeed against a pre-existing bcrypt hash, got %v", err)
	}
	if emp.NIK != "0001" || tokens.AccessToken == "" {
		t.Fatalf("expected valid session, got emp=%+v tokens=%+v", emp, tokens)
	}
}

func TestLoginEmployee_RejectsWrongPassword(t *testing.T) {
	gdb := testutil.NewDB(t)
	hash, _ := bcrypt.GenerateFromPassword([]byte("correct"), bcrypt.DefaultCost)
	if err := gdb.Create(&domain.Employee{NIK: "0001", FullName: "X", PasswordHash: string(hash), IsActive: true}).Error; err != nil {
		t.Fatalf("seed employee: %v", err)
	}

	issuer := authtoken.NewIssuer("test-secret")
	svc := auth.NewService(repo.NewEmployeeRepo(gdb), repo.NewUserRepo(gdb), issuer, repo.NewRevokedTokenRepo(gdb), 15*time.Minute, 30*24*time.Hour)

	_, _, err := svc.LoginEmployee(context.Background(), "0001", "wrong")
	if !errors.Is(err, auth.ErrInvalidCredentials) {
		t.Fatalf("expected ErrInvalidCredentials, got %v", err)
	}
}

// D-3 follow-on: a deactivated employee must not be able to log in --
// FindByNIK filters on is_active, so deactivation genuinely blocks login
// rather than being cosmetic.
func TestLoginEmployee_RejectsDeactivatedEmployee(t *testing.T) {
	gdb := testutil.NewDB(t)
	hash, _ := bcrypt.GenerateFromPassword([]byte("password123"), bcrypt.DefaultCost)
	if err := gdb.Create(&domain.Employee{NIK: "0002", FullName: "Inactive", PasswordHash: string(hash), IsActive: false}).Error; err != nil {
		t.Fatalf("seed employee: %v", err)
	}

	issuer := authtoken.NewIssuer("test-secret")
	svc := auth.NewService(repo.NewEmployeeRepo(gdb), repo.NewUserRepo(gdb), issuer, repo.NewRevokedTokenRepo(gdb), 15*time.Minute, 30*24*time.Hour)

	_, _, err := svc.LoginEmployee(context.Background(), "0002", "password123")
	if !errors.Is(err, auth.ErrInvalidCredentials) {
		t.Fatalf("expected deactivated employee login to fail, got %v", err)
	}
}

// D-24: logout revokes only the specific refresh token presented, not every
// token for that employee/session family.
func TestRefresh_RejectsTokenAfterLogout(t *testing.T) {
	svc := newService(t)
	ctx := context.Background()

	issuer := authtoken.NewIssuer("test-secret")
	refreshA, err := issuer.Generate("1", authtoken.AudienceEmployee, "", time.Hour)
	if err != nil {
		t.Fatalf("generate token A: %v", err)
	}
	refreshB, err := issuer.Generate("1", authtoken.AudienceEmployee, "", time.Hour)
	if err != nil {
		t.Fatalf("generate token B: %v", err)
	}

	if err := svc.Logout(ctx, refreshA); err != nil {
		t.Fatalf("logout: %v", err)
	}

	if _, err := svc.Refresh(ctx, refreshA); !errors.Is(err, auth.ErrInvalidCredentials) {
		t.Fatalf("expected revoked token A to be rejected, got %v", err)
	}
	if _, err := svc.Refresh(ctx, refreshB); err != nil {
		t.Fatalf("expected unrelated token B to remain valid, got %v", err)
	}
}

func TestLogout_IsIdempotentAndToleratesGarbageInput(t *testing.T) {
	svc := newService(t)
	ctx := context.Background()

	issuer := authtoken.NewIssuer("test-secret")
	refresh, err := issuer.Generate("1", authtoken.AudienceEmployee, "", time.Hour)
	if err != nil {
		t.Fatalf("generate token: %v", err)
	}

	if err := svc.Logout(ctx, refresh); err != nil {
		t.Fatalf("first logout: %v", err)
	}
	if err := svc.Logout(ctx, refresh); err != nil {
		t.Fatalf("second logout with the same token must not error: %v", err)
	}
	if err := svc.Logout(ctx, "not-a-real-jwt"); err != nil {
		t.Fatalf("logout with garbage input must not error: %v", err)
	}
}
